profile_name: custom
last_input_dir: E:\__Kalponic Studio Repositories\-Kalponic-Studio-Toolbox-\Apps\KS
  MetaMaker\samples
last_output_dir: E:\__Kalponic Studio Repositories\-Kalponic-Studio-Toolbox-\Apps\KS
  MetaMaker\output
