name: civitai_lora
description: Optimized for CivitAI LoRA training datasets
profile_type: civitai_lora
main_prefix: ''
style_preset: ''
rename_pattern: '{category}_{top_tags}_{YYYYMMDD}_{index}'
max_tags:
  general: 50
normalization:
  taxonomy:
    synonyms: {}
    categories:
      character: subject
      style: style
      quality: quality
      artist: technical
    nsfw_filters:
    - nsfw
    - adult
    - explicit
    priority_tags:
    - character
    - style
    - quality
    banned_tags: []
  case_sensitive: false
  remove_duplicates: true
  sort_by_confidence: true
  min_confidence: 0.1
budget:
  max_tags_per_category:
    subject: 10
    style: 15
    quality: 10
    technical: 15
  diversity_weight: 0.4
  quality_threshold: 0.7
  allocation_rules: {}
models:
  tagger: openclip_vith14.onnx
  detector: yolov11.onnx
  captioner: blip2.onnx
performance:
  threads: 4
  batch_size: 4
  memory_profile: medium
export:
  paired_txt: true
  rename_images: true
  package_zip: true
  write_metadata: true
  write_context_json: true
ui_features:
  review_ui: true
  watch_mode: false
  collaboration: false
